import { CARE_PLAN_CATEGORIES } from "@/lib/carePlanCategories";
import {
  WalkIcon,
  DropletIcon,
  ShirtIcon,
  ToothIcon,
  HandIcon,
  SpeechBubbleIcon,
  EyeIcon,
  LungsIcon,
  AppleIcon,
  CupIcon,
  MoonIcon,
  PillIcon,
  MedicalCrossIcon,
  BrainIcon,
  AssessmentIcon,
  AlertTriangleIcon,
  ShieldAlertIcon,
  PeopleGroupIcon,
  CalendarIcon,
  HomeIcon,
  HeartIcon,
} from "@/components/icons";

const ICONS: Record<string, typeof WalkIcon> = {
  MOBILITY: WalkIcon,
  SKIN_CARE: DropletIcon,
  PERSONAL_HYGIENE: DropletIcon,
  PERSONAL_PRESENTATION: ShirtIcon,
  ORAL_CARE: ToothIcon,
  HAND_FOOT_CARE: HandIcon,
  CONTINENCE_CARE: DropletIcon,
  COMMUNICATION: SpeechBubbleIcon,
  EYESIGHT_HEARING: EyeIcon,
  BREATHING: LungsIcon,
  DIETARY_REQUIREMENTS: AppleIcon,
  EATING_DRINKING: CupIcon,
  SWALLOWING: CupIcon,
  NIGHT_CARE_SLEEPING: MoonIcon,
  MEDICATION: PillIcon,
  MEDICAL_CONDITIONS: MedicalCrossIcon,
  CAPACITY_DECISIONS: BrainIcon,
  BEHAVIOUR: AssessmentIcon,
  PAIN: AlertTriangleIcon,
  INFECTION_PREVENTION: ShieldAlertIcon,
  SOCIAL_ACTIVITIES: PeopleGroupIcon,
  COMMUNITY_APPOINTMENTS: CalendarIcon,
  SAFETY_ENVIRONMENT: HomeIcon,
  END_OF_LIFE: HeartIcon,
};

export const CARE_PLAN_TABS = CARE_PLAN_CATEGORIES.map((c) => ({
  ...c,
  icon: ICONS[c.code],
}));
